services:
  db:
    image: mariadb:latest
    container_name: wp_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wp_app
    depends_on:
      db:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MARIADB_DATABASE}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}

  wiki-db:
    image: postgres:15
    container_name: wp_wiki_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: wikisecret
    volumes:
      - wiki-db-data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wp_wiki
    restart: unless-stopped
    depends_on:
      - wiki-db
    ports:
      - "3001:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: wiki-db
      DB_PORT: 5432
      DB_NAME: wiki
      DB_USER: wikiuser
      DB_PASS: wikisecret
      SECRET_KEY: supersecretkey

  grafana:
    image: grafana/grafana:latest
    container_name: wp_grafana
    restart: unless-stopped
    ports:
      - "3002:3000"

volumes:
  db_data:
  wiki-db-data:
